#include "syj/api/local_api.hpp"
#include "syj/core/cli.hpp"
#include "syj/core/model_registry.hpp"
#include "syj/core/version.hpp"
#include <iostream>
#include <string>
#include <string_view>
namespace {
void usage(){std::cerr<<"Usage:\n  syj model list\n  syj model show <name>\n  syj model scan <directory>\n  syj model load <name> [--memory-budget BYTES] [--context TOKENS]\n  syj run <name> <prompt> [--memory-budget BYTES] [--context TOKENS] [--max-tokens TOKENS]\n  syj serve [--host 127.0.0.1] [--port 8080]\n";}
bool u64(std::string_view s,unsigned long long&o){try{o=std::stoull(std::string(s));return true;}catch(...){return false;}}
bool u32(std::string_view s,unsigned int&o){try{o=static_cast<unsigned int>(std::stoul(std::string(s)));return true;}catch(...){return false;}}
int models(int a,char**v){if(a<3){usage();return 2;}syj::core::ModelRegistry r;std::string c(v[2]);if(c=="list"){auto s=r.load_manifest();if(!s&&s.code!=syj::core::StatusCode::model_not_found){std::cerr<<"ERROR: "<<s.message<<'\n';return 3;}for(const auto&m:r.list_models())std::cout<<m.name<<" | "<<m.architecture<<" | "<<syj::core::memory_tier_name(m.expected_ram_tier)<<" | "<<m.local_path<<'\n';return 0;}if(c=="show"){if(a<4){usage();return 2;}auto s=r.load_manifest();if(!s){std::cerr<<"ERROR: "<<s.message<<'\n';return 3;}syj::core::ModelEntry m;auto g=r.get_model(v[3],m);if(!g){std::cerr<<"ERROR: "<<g.message<<'\n';return 4;}std::cout<<"Name: "<<m.name<<'\n'<<"Architecture: "<<m.architecture<<'\n'<<"Parameters: "<<m.parameter_count<<'\n'<<"Quantization: "<<m.quantization<<'\n'<<"File bytes: "<<m.file_size_bytes<<'\n'<<"RAM tier: "<<syj::core::memory_tier_name(m.expected_ram_tier)<<'\n'<<"Context support: "<<m.context_support<<'\n'<<"Estimated required bytes: "<<m.estimated_required_bytes<<'\n'<<"Local path: "<<m.local_path<<'\n';return 0;}if(c=="scan"){if(a<4){usage();return 2;}auto e=r.load_manifest();if(!e&&e.code!=syj::core::StatusCode::model_not_found){std::cerr<<"ERROR: "<<e.message<<'\n';return 3;}auto s=r.scan_directory(v[3]);if(!s){std::cerr<<"ERROR: "<<s.message<<'\n';return 4;}auto w=r.save_manifest();if(!w){std::cerr<<"ERROR: "<<w.message<<'\n';return 5;}std::cout<<"Registered models: "<<r.list_models().size()<<'\n';return 0;}if(c=="load"){if(a<4){usage();return 2;}syj::cli::LoadOptions o;o.model_name=v[3];for(int i=4;i<a;++i){std::string x(v[i]);if(x=="--memory-budget"&&i+1<a){if(!u64(v[++i],o.memory_budget_bytes))return 2;}else if(x=="--context"&&i+1<a){if(!u32(v[++i],o.context_size))return 2;}else{std::cerr<<"ERROR: unknown option: "<<x<<'\n';return 2;}}return syj::cli::load(o);}std::cerr<<"ERROR: unknown model command: "<<c<<'\n';return 2;}
int run(int a,char**v){if(a<4){usage();return 2;}syj::cli::RunOptions o;o.model_name=v[2];o.prompt=v[3];for(int i=4;i<a;++i){std::string x(v[i]);if(x=="--memory-budget"&&i+1<a){if(!u64(v[++i],o.memory_budget_bytes))return 2;}else if(x=="--context"&&i+1<a){if(!u32(v[++i],o.context_size))return 2;}else if(x=="--max-tokens"&&i+1<a){if(!u32(v[++i],o.max_output_tokens))return 2;}else{return 2;}}return syj::cli::run(o);}
int serve(int a,char**v){syj::api::LocalApiConfig c;for(int i=2;i<a;++i){std::string x(v[i]);if(x=="--host"&&i+1<a)c.host=v[++i];else if(x=="--port"&&i+1<a){try{c.port=std::stoi(v[++i]);}catch(...){return 2;}}else return 2;}if(c.host!="127.0.0.1"&&c.host!="localhost")std::cerr<<"WARNING: API is designed for localhost-only use; requested host is "<<c.host<<'\n';syj::api::LocalApiServer s(c);std::cout<<"SYJ local API listening on "<<c.host<<':'<<c.port<<'\n';if(!s.listen()){std::cerr<<"ERROR: failed to bind local API server\n";return 3;}return 0;}
}
int main(int a,char**v){std::cout<<"SYJ LLM runtime\nVersion: "<<syj::core::version()<<"\nVendor: "<<syj::core::vendor()<<"\nStage: Phase 5 - Fine-Tuning Pipeline\n";if(a<2){usage();return 2;}std::string c(v[1]);if(c=="model")return models(a,v);if(c=="run")return run(a,v);if(c=="serve")return serve(a,v);if(a>=3){return syj::cli::run_path(v[1],v[2]);}usage();return 2;}
